import 'dart:math';

import 'package:flutter_list_pagination/app/app.logger.dart';
import 'package:flutter_list_pagination/models/comments_model.dart';

class CommentsService {
  final log = getLogger('CommentsService');

  final _commentsList = [
    Comments(userName: 'Red', userComment: 'Nice'),
    Comments(userName: 'Gabe', userComment: 'Very good'),
    Comments(userName: 'Mark', userComment: 'Bad'),
    Comments(userName: 'Michael', userComment: 'Nonsense'),
    Comments(userName: 'Odu', userComment: 'Crap'),
    Comments(userName: 'Harry', userComment: 'Excellent'),
    Comments(userName: 'Hannah', userComment: 'Lovely'),
    Comments(userName: 'Hailey', userComment: 'Mad o'),
    Comments(userName: 'Harriet', userComment: 'Wow'),
    Comments(userName: 'Mustapha', userComment: 'You dey vex'),
    Comments(userName: 'Monsey', userComment: 'Awesome'),
    Comments(userName: 'Mario', userComment: 'Hmmmm'),
    Comments(userName: 'Matteo', userComment: 'Needs work'),
    Comments(userName: 'James', userComment: 'Wow'),
    Comments(userName: 'Mariam', userComment: 'Opor'),
    Comments(userName: 'Red', userComment: 'Nice'),
    Comments(userName: 'Gabe', userComment: 'Very good'),
    Comments(userName: 'Mark', userComment: 'Bad'),
    Comments(userName: 'Michael', userComment: 'Nonsense'),
    Comments(userName: 'Odu', userComment: 'Crap'),
    Comments(userName: 'Harry', userComment: 'Excellent'),
    Comments(userName: 'Hannah', userComment: 'Lovely'),
    Comments(userName: 'Hailey', userComment: 'Mad o'),
    Comments(userName: 'Harriet', userComment: 'Wow'),
    Comments(userName: 'Mustapha', userComment: 'You dey vex'),
    Comments(userName: 'Monsey', userComment: 'Awesome'),
    Comments(userName: 'Mario', userComment: 'Hmmmm'),
    Comments(userName: 'Matteo', userComment: 'Needs work'),
    Comments(userName: 'James', userComment: 'Wow'),
    Comments(userName: 'Mariam', userComment: 'Opor'),
    Comments(userName: 'Red', userComment: 'Nice'),
    Comments(userName: 'Gabe', userComment: 'Very good'),
    Comments(userName: 'Mark', userComment: 'Bad'),
    Comments(userName: 'Michael', userComment: 'Nonsense'),
    Comments(userName: 'Odu', userComment: 'Crap'),
    Comments(userName: 'Harry', userComment: 'Excellent'),
    Comments(userName: 'Hannah', userComment: 'Lovely'),
    Comments(userName: 'Hailey', userComment: 'Mad o'),
    Comments(userName: 'Harriet', userComment: 'Wow'),
    Comments(userName: 'Mustapha', userComment: 'You dey vex'),
    Comments(userName: 'Monsey', userComment: 'Awesome'),
    Comments(userName: 'Mario', userComment: 'Hmmmm'),
    Comments(userName: 'Matteo', userComment: 'Needs work'),
    Comments(userName: 'James', userComment: 'Wow'),
    Comments(userName: 'Mariam', userComment: 'Opor'),
    Comments(userName: 'Red', userComment: 'Nice'),
    Comments(userName: 'Gabe', userComment: 'Very good'),
    Comments(userName: 'Mark', userComment: 'Bad'),
    Comments(userName: 'Michael', userComment: 'Nonsense'),
    Comments(userName: 'Odu', userComment: 'Crap'),
    Comments(userName: 'Harry', userComment: 'Excellent'),
    Comments(userName: 'Hannah', userComment: 'Lovely'),
    Comments(userName: 'Hailey', userComment: 'Mad o'),
    Comments(userName: 'Harriet', userComment: 'Wow'),
    Comments(userName: 'Mustapha', userComment: 'You dey vex'),
    Comments(userName: 'Monsey', userComment: 'Awesome'),
    Comments(userName: 'Mario', userComment: 'Hmmmm'),
    Comments(userName: 'Matteo', userComment: 'Needs work'),
    Comments(userName: 'James', userComment: 'Wow'),
    Comments(userName: 'Mariam', userComment: 'Opor'),
    Comments(userName: 'Red', userComment: 'Nice'),
    Comments(userName: 'Gabe', userComment: 'Very good'),
    Comments(userName: 'Mark', userComment: 'Bad'),
    Comments(userName: 'Michael', userComment: 'Nonsense'),
    Comments(userName: 'Odu', userComment: 'Crap'),
    Comments(userName: 'Harry', userComment: 'Excellent'),
    Comments(userName: 'Hannah', userComment: 'Lovely'),
    Comments(userName: 'Hailey', userComment: 'Mad o'),
    Comments(userName: 'Harriet', userComment: 'Wow'),
    Comments(userName: 'Mustapha', userComment: 'You dey vex'),
    Comments(userName: 'Monsey', userComment: 'Awesome'),
    Comments(userName: 'Mario', userComment: 'Hmmmm'),
    Comments(userName: 'Matteo', userComment: 'Needs work'),
    Comments(userName: 'James', userComment: 'Wow'),
    Comments(userName: 'Mariam', userComment: 'Opor'),
    Comments(userName: 'Red', userComment: 'Nice'),
    Comments(userName: 'Gabe', userComment: 'Very good'),
    Comments(userName: 'Mark', userComment: 'Bad'),
    Comments(userName: 'Michael', userComment: 'Nonsense'),
    Comments(userName: 'Odu', userComment: 'Crap'),
    Comments(userName: 'Harry', userComment: 'Excellent'),
    Comments(userName: 'Hannah', userComment: 'Lovely'),
    Comments(userName: 'Hailey', userComment: 'Mad o'),
    Comments(userName: 'Harriet', userComment: 'Wow'),
    Comments(userName: 'Mustapha', userComment: 'You dey vex'),
    Comments(userName: 'Monsey', userComment: 'Awesome'),
    Comments(userName: 'Mario', userComment: 'Hmmmm'),
    Comments(userName: 'Matteo', userComment: 'Needs work'),
    Comments(userName: 'James', userComment: 'Wow'),
    Comments(userName: 'Mariam', userComment: 'Opor'),
    Comments(userName: 'Red', userComment: 'Nice'),
    Comments(userName: 'Gabe', userComment: 'Very good'),
    Comments(userName: 'Mark', userComment: 'Bad'),
    Comments(userName: 'Michael', userComment: 'Nonsense'),
    Comments(userName: 'Odu', userComment: 'Crap'),
    Comments(userName: 'Harry', userComment: 'Excellent'),
    Comments(userName: 'Hannah', userComment: 'Lovely'),
    Comments(userName: 'Hailey', userComment: 'Mad o'),
    Comments(userName: 'Harriet', userComment: 'Wow'),
    Comments(userName: 'Mustapha', userComment: 'You dey vex'),
    Comments(userName: 'Monsey', userComment: 'Awesome'),
    Comments(userName: 'Mario', userComment: 'Hmmmm'),
    Comments(userName: 'Matteo', userComment: 'Needs work'),
    Comments(userName: 'James', userComment: 'Wow'),
    Comments(userName: 'Mariam', userComment: 'Opor'),
    Comments(userName: 'Red', userComment: 'Nice'),
    Comments(userName: 'Gabe', userComment: 'Very good'),
    Comments(userName: 'Mark', userComment: 'Bad'),
    Comments(userName: 'Michael', userComment: 'Nonsense'),
    Comments(userName: 'Odu', userComment: 'Crap'),
    Comments(userName: 'Harry', userComment: 'Excellent'),
    Comments(userName: 'Hannah', userComment: 'Lovely'),
    Comments(userName: 'Hailey', userComment: 'Mad o'),
    Comments(userName: 'Harriet', userComment: 'Wow'),
    Comments(userName: 'Mustapha', userComment: 'You dey vex'),
    Comments(userName: 'Monsey', userComment: 'Awesome'),
    Comments(userName: 'Mario', userComment: 'Hmmmm'),
    Comments(userName: 'Matteo', userComment: 'Needs work'),
    Comments(userName: 'James', userComment: 'Wow'),
    Comments(userName: 'Mariam', userComment: 'Opor'),
    Comments(userName: 'Red', userComment: 'Nice'),
    Comments(userName: 'Gabe', userComment: 'Very good'),
    Comments(userName: 'Mark', userComment: 'Bad'),
    Comments(userName: 'Michael', userComment: 'Nonsense'),
    Comments(userName: 'Odu', userComment: 'Crap'),
    Comments(userName: 'Harry', userComment: 'Excellent'),
    Comments(userName: 'Hannah', userComment: 'Lovely'),
    Comments(userName: 'Hailey', userComment: 'Mad o'),
    Comments(userName: 'Harriet', userComment: 'Wow'),
    Comments(userName: 'Mustapha', userComment: 'You dey vex'),
    Comments(userName: 'Monsey', userComment: 'Awesome'),
    Comments(userName: 'Mario', userComment: 'Hmmmm'),
    Comments(userName: 'Matteo', userComment: 'Needs work'),
    Comments(userName: 'James', userComment: 'Wow'),
    Comments(userName: 'Mariam', userComment: 'Opor'),
    Comments(userName: 'Red', userComment: 'Nice'),
    Comments(userName: 'Gabe', userComment: 'Very good'),
    Comments(userName: 'Mark', userComment: 'Bad'),
    Comments(userName: 'Michael', userComment: 'Nonsense'),
    Comments(userName: 'Odu', userComment: 'Crap'),
    Comments(userName: 'Harry', userComment: 'Excellent'),
    Comments(userName: 'Hannah', userComment: 'Lovely'),
    Comments(userName: 'Hailey', userComment: 'Mad o'),
    Comments(userName: 'Harriet', userComment: 'Wow'),
    Comments(userName: 'Mustapha', userComment: 'You dey vex'),
    Comments(userName: 'Monsey', userComment: 'Awesome'),
    Comments(userName: 'Mario', userComment: 'Hmmmm'),
    Comments(userName: 'Matteo', userComment: 'Needs work'),
    Comments(userName: 'James', userComment: 'Wow'),
    Comments(userName: 'Mariam', userComment: 'Opor'),
    Comments(userName: 'Red', userComment: 'Nice'),
    Comments(userName: 'Gabe', userComment: 'Very good'),
    Comments(userName: 'Mark', userComment: 'Bad'),
    Comments(userName: 'Michael', userComment: 'Nonsense'),
    Comments(userName: 'Odu', userComment: 'Crap'),
    Comments(userName: 'Harry', userComment: 'Excellent'),
    Comments(userName: 'Hannah', userComment: 'Lovely'),
    Comments(userName: 'Hailey', userComment: 'Mad o'),
    Comments(userName: 'Harriet', userComment: 'Wow'),
    Comments(userName: 'Mustapha', userComment: 'You dey vex'),
    Comments(userName: 'Monsey', userComment: 'Awesome'),
    Comments(userName: 'Mario', userComment: 'Hmmmm'),
    Comments(userName: 'Matteo', userComment: 'Needs work'),
    Comments(userName: 'James', userComment: 'Wow'),
    Comments(userName: 'Mariam', userComment: 'Opor'),
    Comments(userName: 'Red', userComment: 'Nice'),
    Comments(userName: 'Gabe', userComment: 'Very good'),
    Comments(userName: 'Mark', userComment: 'Bad'),
    Comments(userName: 'Michael', userComment: 'Nonsense'),
    Comments(userName: 'Odu', userComment: 'Crap'),
    Comments(userName: 'Harry', userComment: 'Excellent'),
    Comments(userName: 'Hannah', userComment: 'Lovely'),
    Comments(userName: 'Hailey', userComment: 'Mad o'),
    Comments(userName: 'Harriet', userComment: 'Wow'),
    Comments(userName: 'Mustapha', userComment: 'You dey vex'),
    Comments(userName: 'Monsey', userComment: 'Awesome'),
    Comments(userName: 'Mario', userComment: 'Hmmmm'),
    Comments(userName: 'Matteo', userComment: 'Needs work'),
    Comments(userName: 'James', userComment: 'Wow'),
    Comments(userName: 'Mariam', userComment: 'Opor'),
    Comments(userName: 'Red', userComment: 'Nice'),
    Comments(userName: 'Gabe', userComment: 'Very good'),
    Comments(userName: 'Mark', userComment: 'Bad'),
    Comments(userName: 'Michael', userComment: 'Nonsense'),
    Comments(userName: 'Odu', userComment: 'Crap'),
    Comments(userName: 'Harry', userComment: 'Excellent'),
    Comments(userName: 'Hannah', userComment: 'Lovely'),
    Comments(userName: 'Hailey', userComment: 'Mad o'),
    Comments(userName: 'Harriet', userComment: 'Wow'),
    Comments(userName: 'Mustapha', userComment: 'You dey vex'),
    Comments(userName: 'Monsey', userComment: 'Awesome'),
    Comments(userName: 'Mario', userComment: 'Hmmmm'),
    Comments(userName: 'Matteo', userComment: 'Needs work'),
    Comments(userName: 'James', userComment: 'Wow'),
    Comments(userName: 'Mariam', userComment: 'Opor'),
    Comments(userName: 'Red', userComment: 'Nice'),
    Comments(userName: 'Gabe', userComment: 'Very good'),
    Comments(userName: 'Mark', userComment: 'Bad'),
    Comments(userName: 'Michael', userComment: 'Nonsense'),
    Comments(userName: 'Odu', userComment: 'Crap'),
    Comments(userName: 'Harry', userComment: 'Excellent'),
    Comments(userName: 'Hannah', userComment: 'Lovely'),
    Comments(userName: 'Hailey', userComment: 'Mad o'),
    Comments(userName: 'Harriet', userComment: 'Wow'),
    Comments(userName: 'Mustapha', userComment: 'You dey vex'),
    Comments(userName: 'Monsey', userComment: 'Awesome'),
    Comments(userName: 'Mario', userComment: 'Hmmmm'),
    Comments(userName: 'Matteo', userComment: 'Needs work'),
  ];

  Future<List<Comments>?> getComments({required int currentPage}) async {
    int itemsPerPage = 15;
    final fetchedList = <Comments>[];
    final itemsLeft =
        min(itemsPerPage, _commentsList.length - currentPage * itemsPerPage);
    log.i('Now on page $currentPage');
    await Future.delayed(const Duration(seconds: 2));
    for (int i = 0; i < itemsLeft; i++) {
      fetchedList.add(_commentsList[i]);
    }
    log.i(
        'items per page: $itemsPerPage Current page: $currentPage, Count: ${_commentsList.length}');
    return fetchedList;
  }
}
